### ISSUE TITLE
Fix docs page container dark mode

### ISSUE THREAD

**Issue by smolinari** [dreamonkey/quasar#103]
@IlCallo - I've tried to get the dark mode running, but somehow the docs landing page has some strange override over the dark mode background within the page-container. And, I'm too much of a noob to figure out why dark mode is broken in the page container in the docs. 

I'm not sure if you have the time to figure out the problem. I'm blocked because of it. 

If anyone else would like to take a poke at troubleshooting, please do. It would be greatly appreciated.

Scott

**Comment by IlCallo** [comment]
I won't have a pc at my hands until Monday, can you tell me how to reproduce the issue and what's the name of the branch you're working on?

**Comment by smolinari** [comment]
Working with dev branch (but in another branch) and all you need to do is add `$q.dark.set(true)` in the `DocLayout.vue`. 

Scott

**Comment by IlCallo** [comment]
![image](https://user-images.githubusercontent.com/10036108/154933001-27972d8d-6690-4ffb-bf6f-3bb98c6a2c33.png)

Into `DocLayout.vue`. That's what is causing the greish background. If you remove it from there, you'll need to add it back for light mode in some other way
It have higher priority because the class it has `!important` (as other `text-*` and `bg-*` classes from Quasar core as `bg-primary`)
Removing `!important` from the definition (into `docs/src/css/landing-page/utilities.scss` loop at line 18) would probably cause some other styling to not work, but feel free to remove it and see if it causes problems anywhere, if you cannot find another solution

**Comment by smolinari** [comment]
@IlCallo - Thanks. I'll have a look at it. Thanks for digging. I missed that completely and it is strange it wasn't visible to me in dev tools. But, "oh well". 🤷 

Scott

**Comment by IlCallo** [comment]
You had to check the "computed" sub-tab of the dev tools, then check out container elements one by one "bubbling up" (check the current element, then the parent, then the parent, etc)
When you find the computed background-color set, you know the rule is applied to that element, you switch back to the rules sub-tab and you can see the selector applying the rule
