### ISSUE TITLE
Not wild about the typography

### ISSUE THREAD

**Issue by geoidesic** [dreamonkey/quasar#126]
**Description**
_Clearly and concisely explain the problem.
You can mention unclear or missing information, typos, grammatical mistakes, etc.
Any contributions and suggestions are welcome!_

The typography in general has wide kerning everywhere and is centered horizontally, which makes everything harder to read (i.e. slower to parse).

**Website Section URL**
_[Website live preview](https://quasar.beget.it), paste the page URL or section name (eg. Docs, if it happens on all docs page) below._

Whole site.

**Comment by NiccoloMenozzi** [comment]
Good point. The typography in the new pages is aligned with the brand guidelines approved 1 year ago and it has been purposefully limited to a few pages where we needed a stronger brand identity and/or where the text length is short enough to minimize the effect you are describing. For example, all the pages inside the docs section where you can read documentation has not been changed at all, exactly for the same reasons.
We know how important is to keep long text readable at its best. Docs doesn't need branding, there the focus is on work rather than visual communication.

However we will use the future survey to check if this choice has actually a negative impact on a meaningful % of people.
