### ISSUE TITLE
Add some vertical space to drawer items on mobile

### ISSUE THREAD

**Issue by IlCallo** [dreamonkey/quasar#72]
**Description**
_Clearly and concisely explain the problem.
You can mention unclear or missing information, typos, grammatical mistakes, etc.
Any contributions and suggestions are welcome!_

From Aldrin:
> The menu items probably need some y padding, they look very close to each other in mobile almost zoomed for me

@NiccoloMenozzi what do you think?

**Website Section URL**
_[Website live preview](https://quasar.beget.it), paste the page URL or section name (eg. Docs, if it happens on all docs page) below._

Everywhere

**Comment by NiccoloMenozzi** [comment]
We can increase the size for mobile devices in order to improve the tapping area but I would wait for the desktop part. The new denseness is nothing really out of standard (36 pxl) and it will help navigate pages while reducing a bit the necessity to scroll. It also helps reducing a bit the material look-and-feel in favor of a stronger identity. As far as the pages are so many as now, it is absolutely acceptable to adopt a dense items list.

**Comment by IlCallo** [comment]
From Luke too

> left drawer could be spaced out a little more
> Left drawer spaced out basically means a bit of padding above and below the list items
